### ISSUE TITLE
Bel levelling plugin

### ISSUE THREAD

**Issue by tmirante** [thopiekar/CuraInventorPlugin#5]
Sorry for trouble but i see you are involved in plugin development. I was looking to develop a plugin that was available in old verion of cyra and disappeared now , or better it is for some type of printers and not for all it is the bed levelling. I should like to understand why i am not able to pack it  in the right manner . i got _init_ file and changed it  using python installation with uranium as required . How i can now install and test it in cura? . in last version (3.3.1) . prepared it copying from Ultmaker bed levelling and trying to install like a plugin to create a script to have it in extension menu ( looking at AutoOrientation Plugin) . Porpouse of plugin is to create a way in which i can tune my personal bed level parameters and lauch the script to do the bed level as i like in diferent points. .thanks for any hint or help 
[TMBedLevelMachineAction.zip](https://github.com/thopiekar/CuraInventorPlugin/files/1950713/TMBedLevelMachineAction.zip)

**Comment by thopiekar** [comment]
Hey @tmirante,

There are some details missing about your development environment. Which OS are you using?
All I know is that when changed something to the API or at least had a good reason to dump the enum of the API version. Maybe it is enough to change the version of your plugin in the JSON from 4 to 5.

Regards!

**Comment by tmirante** [comment]
Thanks for your answer.  My system is Windows 10 . I work with python 3.6 64 bit using charm.I was able ti create the package using your script, and i istalled it on cura 3.2.1  but i was not able to find it on extension menu as expected from what I wrote on init. On 3.3.1 i not find a way to install new plugin. May you let me know why I not find it on extension menu?

**Comment by thopiekar** [comment]
Ah, now I understand. In the past there was a possibility to install plugins manually via plugin package.

Alternatively, you can place your source code by hand into %AppData%/Roaming/cura/3.3/plugins/<your plugin's name>/<your plugin's name>
.. and edit your code directly there. But to make changes take effect you'll need to restart cura.

Hope this will answer your question better 😁

**Comment by tmirante** [comment]
ok thanks perfect . i did and restarted  but nothing happens. i suppose to have an error in preparing  the menu  , ultimaker only uses the bed tuning so i suppose the point @action position the menu in ultimaker only . i have not the right idea of cura enviroment  trying to define it form listings of plugins. thanks . you may close i will go looking for

**Comment by thopiekar** [comment]
No problem. It is very easy to make mistakes in QML files and worst of all (but that might changed already) you don't get much info about the crash.
Noticed that you opened a new repository with your plugin. Wish you success on your plugin! :+1:
