### ISSUE TITLE
Imported files should auto-populate empty project name

### ISSUE THREAD

**Issue by inkychris** [thopiekar/CuraInventorPlugin#6]
Currently, if I load an STL, the Cura project name is automatically set to the name of the STL file if the project was empty. When loading Inventor files, the project name is set to "unnamed". It would be nice for this plugin to behave similarly to loading STLs and update this field to the name of the Inventor file loaded as this name then auto-populates the gcode file name in the "save to file" window.

**Comment by thopiekar** [comment]
Hey! I also got a mail about the same problem.
Are you the same person, who wrote me the mail?

About your problem: Could you tell me which version of Cura you are using and which Autodesk Inventor is installed?

Thanks!

**Comment by inkychris** [comment]
Hi, I didn't message you privately about this. I'm using Cura 3.4.1 at the moment with Inventor 2018.

**Comment by thopiekar** [comment]
Ok. Good to know. Then it already affects two people.

Will try to take a look onto it tomorrow. (Without any guarantees.)
